/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;


public class Confirmar extends javax.swing.JFrame {

    /**
     * Creates new form Comfirmar
     */
    public Confirmar() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 33, 33));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        eliminarArchivo = new javax.swing.JButton();
        selectTodos = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        elementos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 780));
        setMinimumSize(new java.awt.Dimension(430, 780));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SoyVirus", "1kilogramo", ".com", "El mojan"},
                {"ElDatos", "1tonelada", ".exe", "san francisco"},
                {"Gta", "2g", ".exe", null},
                {"dsfd", "f", "f", "f"},
                {"d", "f", "d", "f"},
                {"d", "d", "f", "d"},
                {"f", "s", "a", "a"},
                {"a", "a", "a", "f"},
                {"f", "s", "s", "f"},
                {"f", "j", "u", "g"}
            },
            new String [] {
                "Nombre", "Tamaño", "Tipo ", "Ruta "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaArchivos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 410, -1));

        eliminarArchivo.setBackground(new java.awt.Color(239, 244, 240));
        eliminarArchivo.setText("Eliminar");
        eliminarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, -1, -1));

        selectTodos.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        selectTodos.setText("Seleccionar Todos");
        selectTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTodosActionPerformed(evt);
            }
        });
        getContentPane().add(selectTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(239, 244, 240));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        elementos1.setBackground(new java.awt.Color(4, 72, 96));
        elementos1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        elementos1.setForeground(new java.awt.Color(4, 72, 96));
        elementos1.setText("Elementos Encontrados");
        getContentPane().add(elementos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 260, -1));

        jLabel1.setBackground(new java.awt.Color(239, 244, 240));
        jLabel1.setMaximumSize(new java.awt.Dimension(430, 780));
        jLabel1.setMinimumSize(new java.awt.Dimension(430, 780));
        jLabel1.setPreferredSize(new java.awt.Dimension(430, 780));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarArchivoActionPerformed
         // Mensaje del diálogo
        String message = "¿Deseas eliminar los archivos seleccionados?";

        // Títulos de los botones personalizados
        String[] options = {"Sí", "No", "Cancelar"};

        // Crear el diálogo personalizado
        int option = JOptionPane.showOptionDialog(
            null,                         // Componente padre (null para centrar)
            message,                      // Mensaje del diálogo
            "Confirmación",               // Título de la ventana
            JOptionPane.YES_NO_CANCEL_OPTION, // Tipos de botones (sí, no, cancelar)
            JOptionPane.QUESTION_MESSAGE,  // Tipo de ícono
            null,                         // Icono personalizado (null para el predeterminado)
            options,                      // Títulos personalizados para los botones
            options[0]                    // Botón predeterminado
        );

        // Mostrar qué botón fue presionado
        if (option == JOptionPane.YES_OPTION) {
           JOptionPane.showMessageDialog(null, "Archivos Borrados","Confirmado", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_eliminarArchivoActionPerformed

    private void selectTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModuloPrincipal volver = new ModuloPrincipal();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elementos1;
    private javax.swing.JButton eliminarArchivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox selectTodos;
    private javax.swing.JTable tablaArchivos;
    // End of variables declaration//GEN-END:variables
}
